[package]
name = "rsysmon"
version = "0.1.3"
edition = "2024"
description = "A Linux system monitoring tool"
license = "MIT"
repository = "https://github.com/MohamedGonem/sysmon"
readme = "README.md"

[[bin]]
name = "sysmon"
path = "src/main.rs"

[dependencies]
colored = "2"
clap = { version = "4", features = ["derive"] }

[features]
default = ["cpu", "mem", "bat", "tmux"]
cpu = []
mem = []
bat = []
tmux = []
