[package]
name = "rsysmon"
version = "0.1.4"
edition = "2024"
description = "A Linux system monitoring tool"
license = "MIT"
repository = "https://github.com/MohamedGonem/sysmon"
readme = "README.md"

[[bin]]
name = "sysmon"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }

[features]
default = ["sys","cpu", "mem", "bat", "tmux"]
sys = ["tmux"]
cpu = ["tmux"]
mem = ["tmux"]
bat = ["tmux"]
tmux = []
