[package]
name = "rsysmon"
version = "0.1.1"
edition = "2024"
description = "A Linux system monitoring tool"
license = "MIT"
repository = "https://github.com/MohamedGonem/sysmon"

[[bin]]
name = "sysmon"
path = "src/main.rs"

[dependencies]
colored = "2"
clap = { version = "4", features = ["derive"] }
